In [1]:
######## Importation des bibliothèques

import numpy as np
import matplotlib.pyplot as plt

In [2]:
######## échauffement : le broadcasting

a = np.array([1,2,3])

#1
print(np.shape(a[:,None]),a[:,None]) #on rajoute une dimension a 'droite' --> vecteur colonne (3,1)
print(np.shape(a[None,:]),a[None,:]) #on rajoute une dimension a 'gauche' --> un tableau dans un tableau (1,3)

#2
print(np.shape(a[:,None]-a[None,:]),a[:,None]-a[None,:]) #on etend la première matrice pr qu'elle ait 3 colonnes, on etend la seconde pour qu'elle ai 3 lignes

#3
b = np.arange(1,7).reshape(2,3)
print(b[:,None,:]) #on crée des matrices autour de celle déja existantes (des matrices de matrices)
print(b[:,:,None]) #on crée 2 matrices avec 3 matrices dedans (les plus petites matrices ont 1 élément)
print(np.shape(b[:,None,:]-b[::,None]),b[:,None,:]-b[:,:,None]) 


(3, 1) [[1]
 [2]
 [3]]
(1, 3) [[1 2 3]]
(3, 3) [[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]
[[[1 2 3]]

 [[4 5 6]]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
(2, 1, 3) [[[ 0  1  2]
  [-1  0  1]
  [-2 -1  0]]

 [[ 0  1  2]
  [-1  0  1]
  [-2 -1  0]]]


In [ ]:
######## initialiation aléatoire
# les borens pour le tirage au sort initial
mass_max=3

x_min, x_max = -10., 10.
y_min, y_max = -10., 10.

speed_max = 1

def init_problem(N):
    masses = np.random.uniform(0.01,mass_max,N)
    minimums = np.array([[x_min], [y_min]]) # on veut que la première ligne soit en x et la seconde en y, par broadcasting ça va s'étandre sur les N colonnes
    maximums = np.array([[x_max],[y_max]])
    positions = np.random.uniform(minimums, maximums, (2,N))
    speeds = np.random.uniform(0.01,speed_max,(2,N)) #on cree un tableau de vx et vy en broadcastant les v_min et v_max
    return masses, positions, speeds

masses, positions, speeds = init_problem(10)
try:
    assert masses.shape == (10,) and positions.shape == speeds.shape == (2,10) 
    print("OK")
except:
    print("KO")

OK


In [ ]:
######## initialisation reproductible