In [1]:
######## Importation des bibliothèques

import numpy as np
import matplotlib.pyplot as plt

In [ ]:
######## échauffement : le broadcasting

a = np.array([1,2,3])

#1
print(np.shape(a[:,None]),a[:,None]) #on rajoute une dimension a 'droite' --> vecteur colonne (3,1)
print(np.shape(a[None,:]),a[None,:]) #on rajoute une dimension a 'gauche' --> un tableau dans un tableau (1,3)

#2
print(np.shape(a[:,None]-a[None,:]),a[:,None]-a[None,:]) #on etend la première matrice pr qu'elle ait 3 colonnes, on etend la seconde pour qu'elle ai 3 lignes

#3
b = np.arange(1,7).reshape(2,3)
print(b[:,None,:]) #on crée des matrices autour de celle déja existantes (des matrices de matrices)
print(b[:,:,None]) #on crée 2 matrices avec 3 matrices dedans (les plus petites matrices ont 1 élément)
print(np.shape(b[:,None,:]-b[::,None]),b[:,None,:]-b[:,:,None]) 


(3, 1) [[1]
 [2]
 [3]]
(1, 3) [[1 2 3]]
(3, 3) [[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]
[[[1 2 3]]

 [[4 5 6]]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
(2, 1, 3) [[[ 0  1  2]
  [-1  0  1]
  [-2 -1  0]]

 [[ 0  1  2]
  [-1  0  1]
  [-2 -1  0]]]
